/*
 * Created 2015-11-28 21:56:59
 */
package io.github.azige.moebooruviewer;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.util.HashMap;
import java.util.Map;

import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Azige
 */
public class ShowPostFrame extends javax.swing.JFrame{

    private static final Logger logger = LoggerFactory.getLogger(ShowPostFrame.class);
    private Map<Long, ShowPostPanel> postPanelMap = new HashMap<>();

    /**
     * Creates new form PostFrame
     */
    public ShowPostFrame(){
        initComponents();
        tabbedPane.addChangeListener(new ChangeListener(){

            @Override
            public void stateChanged(ChangeEvent e){
                ShowPostPanel postPanel = (ShowPostPanel)tabbedPane.getSelectedComponent();
                if (postPanel != null){
                    postPanel.updateImage();
                }
            }
        });
        tabbedPane.addMouseListener(new MouseAdapter(){

            @Override
            public void mouseClicked(MouseEvent e){
                if (SwingUtilities.isLeftMouseButton(e) && e.getClickCount() == 2){
                    ShowPostPanel postPanel = (ShowPostPanel)tabbedPane.getSelectedComponent();
                    tabbedPane.remove(postPanel);
                    postPanelMap.values().remove(postPanel);
                    if (postPanelMap.isEmpty()){
                        setVisible(false);
                    }
                }
            }

        });
        rootPane.addComponentListener(new ComponentAdapter(){

            @Override
            public void componentResized(ComponentEvent e){
                ShowPostPanel postPanel = (ShowPostPanel)tabbedPane.getSelectedComponent();
                if (postPanel != null){
                    postPanel.updateImage();
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setTitle("Post");
        setMinimumSize(new java.awt.Dimension(800, 650));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 650));
        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showPost(Post post){
        ShowPostPanel postPanel = postPanelMap.get(post.getId());
        if (postPanel == null){
            postPanel = new ShowPostPanel();
            postPanel.showPost(post);
            tabbedPane.addTab(String.valueOf(post.getId()), postPanel);
            postPanelMap.put(post.getId(), postPanel);
        }
        tabbedPane.setSelectedComponent(postPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
