/*
 * Created 2015-11-28 21:56:59
 */
package io.github.azige.moebooruviewer;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Azige
 */
public class ShowPostFrame extends javax.swing.JFrame{

    private Post presentingPost;
    private Image image;

    /**
     * Creates new form PostFrame
     */
    public ShowPostFrame(){
        initComponents();
        postLabel.addComponentListener(new ComponentAdapter(){

            @Override
            public void componentResized(ComponentEvent e){
                if (image != null){
                    showImage();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postLabel = new javax.swing.JLabel();
        tagPanel = new javax.swing.JPanel();
        toolPanel = new javax.swing.JPanel();
        downloadLabel = new javax.swing.JLabel();

        setTitle("Post");
        setMinimumSize(new java.awt.Dimension(800, 650));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 650));

        postLabel.setBackground(new java.awt.Color(0, 0, 0));
        postLabel.setForeground(new java.awt.Color(255, 255, 255));
        postLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        postLabel.setText("加载中……");
        postLabel.setOpaque(true);
        postLabel.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(postLabel, java.awt.BorderLayout.CENTER);

        tagPanel.setBackground(new java.awt.Color(0, 0, 0));
        tagPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tagPanel.setLayout(new javax.swing.BoxLayout(tagPanel, javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(tagPanel, java.awt.BorderLayout.LINE_START);

        toolPanel.setBackground(new java.awt.Color(0, 0, 0));
        toolPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        toolPanel.setLayout(new javax.swing.BoxLayout(toolPanel, javax.swing.BoxLayout.Y_AXIS));

        downloadLabel.setForeground(new java.awt.Color(255, 255, 255));
        downloadLabel.setText("下载大图");
        downloadLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        downloadLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downloadLabelMouseClicked(evt);
            }
        });
        toolPanel.add(downloadLabel);

        getContentPane().add(toolPanel, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void downloadLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadLabelMouseClicked
        postLabel.setIcon(null);
        postLabel.setText("加载中……");
        MoebooruViewer.execute(() -> {
            image = MoebooruViewer.getNetIO().loadOrigin(presentingPost);
            SwingUtilities.invokeLater(() -> {
                if (image != null){
                    showImage();
                }else{
                    postLabel.setText("加载失败！");
                }
            });
        });
    }//GEN-LAST:event_downloadLabelMouseClicked

    public void showPost(Post post){
        postLabel.setIcon(null);
        postLabel.setText("加载中……");
        setTitle("Post[" + post.getId() + "]");

        presentingPost = post;
        MoebooruViewer.execute(() -> {
            image = MoebooruViewer.getNetIO().loadSample(post);
            SwingUtilities.invokeLater(() -> {
                if (presentingPost == post){
                    if (image != null){
                        showImage();
                    }else{
                        postLabel.setText("加载失败！");
                    }
                }
            });
        });

        tagPanel.removeAll();
        for (String tagName : post.getTags().split(" ")){
            JLabel label = new JLabel(tagName);
            label.setForeground(Color.WHITE);
            label.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            label.addMouseListener(new MouseAdapter(){

                @Override
                public void mouseClicked(MouseEvent e){
                    new ListPostFrame(tagName).setVisible(true);
                }

            });
            tagPanel.add(label);
            MoebooruViewer.execute(() -> {
                Tag tag = MoebooruViewer.getNetIO().retry(() -> MoebooruViewer.getMAPI().findTag(tagName));
                if (tag != null){
                    SwingUtilities.invokeLater(() -> {
                        switch (tag.getType()){
                            case Tag.TYPE_GENERAL:
                                label.setForeground(Color.decode("0xEE8887"));
                                break;
                            case Tag.TYPE_ARTIST:
                                label.setForeground(Color.decode("0xCCCC00"));
                                break;
                            case Tag.TYPE_COPYRIGHT:
                                label.setForeground(Color.decode("0xDD00DD"));
                                break;
                            case Tag.TYPE_CHARACTER:
                                label.setForeground(Color.decode("0x00AA00"));
                                break;
                        }
                    });
                }
            });
        }
        tagPanel.repaint();
    }

    private void showImage(){
        postLabel.setText("");
        postLabel.setIcon(new ImageIcon(MoebooruViewer.resizeImage(image, postLabel.getWidth(), postLabel.getHeight())));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel downloadLabel;
    private javax.swing.JLabel postLabel;
    private javax.swing.JPanel tagPanel;
    private javax.swing.JPanel toolPanel;
    // End of variables declaration//GEN-END:variables
}
